config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # order of routes matters, if new is after :id then we would never land in new page
  get "blog_posts/new", to: "blog_posts#new" , as: :new_blog_post
  get "/blog_posts/:id/edit", to:"blog_posts#edit", as: :edit_blog_post
  # In Rails' routes.rb file, routes are defined to map incoming requests to the appropriate controller and action that should handle the request. The get method is used to define a route that responds to an HTTP GET request.
  # The route get "blog_posts/:id" , "blog_post#show" maps the URL "/blog_posts/:id" to the show action in the BlogPostController controller. The :id portion of the URL is a dynamic segment that will match any value and pass it to the show action as a parameter.
  get "blog_posts/:id", to: "blog_posts#show", as: :blog_post
# Generated automatically
# blog_post_path(1) ==> "/blog_posts/1
# blog_post_url(1) ==> "http://localhost:3000/blog_posts/1
# =================================================================================================
# So, when you submit the form generated by form_with in the view, the form data will be sent as a POST request to the URL path /blog_posts. The create action in the BlogPostsController will receive this request, and it will create a new BlogPost object based on the submitted form data.
  post "/blog_posts", to: "blog_posts#create", as: :blog_posts
# =================================================================================================
  # Since we already have a path for this route in line 9 we don't need to specify a new name (Routes are just strings and Rails doesn't care what type of request it is)
  # To see why this became our route, try clicking on the update btn and check the html in inspector, you see that the form is gonna be submitted to this route and not /blog_posts/:id/edit
  patch "/blog_posts/:id", to:"blog_posts#update" 
 # =================================================================================================

  delete "/blog_posts/:id", to:"blog_posts#destroy"


# =================================================================================================================================================================
# Instead of defining routes one by one we can use a rails helper called resources
# resources :blog_posts
# This also comes with a new route called : get "/blog_posts" , to: "blog_posts#index", as: :blog_posts


  # Defines the root path route ("/") ==> if we remove this the home page would be the default rails homepage so we won't remove the line below
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title ,presence:true ,length: { minimum: 2, maximum: 60, message: "Should be between 2 and 60 characters" }
    validates :body , presence:true ,length: { minimum:5, message:"Should be more than 5 characters" }

    scope :sorted, -> { order(published_at: :desc, updated_at: :desc)}
    scope :draft, -> { where(published_at: nil)}
    scope :scheduled, -> {where("published_at >= ?" , Time.current)}
    scope :published, -> {where("published_at < ?" , Time.current)}

    # In this code, published_at? is a shorthand way to check if the published_at attribute is present (i.e., not nil or false). The ? at the end of the method name is a convention in Ruby to indicate that the method returns a boolean value, i.e., either true or false. So, in this case, the draft? method returns true if the published_at attribute is present (i.e., the post is not a draft), and false otherwise (i.e., the post is a draft).

    def draft?
        published_at.nil?
    end

    def published?
        published_at? && published <= Time.current
    end

    def scheduled?
        published_at? && published_at > Time.current
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user! , except:[:show, :index]
    before_action :set_blog_post, except:[:index , :new, :create]

    # Yes, you can remove the .all from BlogPost.sorted.all. By default, when you call a scope in Rails, it returns an ActiveRecord::Relation object, which is lazy loaded. This means that the actual SQL query is only executed when you try to access the results of the relation, such as when you call methods like each, count, or to_a.

    # Therefore, adding .all to the end of the scope chain is redundant in this case, as it does not change the behavior of the query. You can safely remove it and the code will still work correctly:
    def index
        #  @blog_posts = user_signed_in? ? BlogPost.sorted.all : BlogPost.sorted.published
        @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.sorted.published
    end

    def show
        # @blog_post = BlogPost.find(params[:id])
    # rescue ActiveRecord::RecordNotFound
    #     redirect_to root_path
    end

    def new
        @blog_post = BlogPost.new
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new , status: :unprocessable_entity
        end
    end

    def edit
        # @blog_post = BlogPost.find(params[:id])
    end


    def update
        # @blog_post = BlogPost.find(params[:id])
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else 
            render :edit , status: :unprocessable_entity
        end
    end

    def destroy 
        # @blog_post = BlogPost.find(params[:id])
        @blog_post.destroy()
        redirect_to root_path
    end

    # The purpose of the method is to define a "strong parameters" whitelist of the parameters that are allowed to be passed into the create and update actions of the controller. It does this by taking the params object, which is a hash containing all the HTTP parameters that were sent in the request, and calling the require method on it with the key :blog_post. This ensures that only parameters that are associated with a blog_post object will be permitted.

    # Then, the permit method is called on the resulting object to specify which attributes of the blog_post object are allowed to be mass-assigned. In this case, the :title and :body attributes are permitted, which means that only those parameters will be used to create or update the blog_post object in the database.

    private 
    def blog_post_params
        params.require(:blog_post).permit(:title, :body, :published_at)
    end

    def set_blog_post
        @blog_post  =  user_signed_in? ? BlogPost.find(params[:id]) :BlogPost.published.find(params[:id])
        
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post, local: true do |form| %>
  <div class="mb-4">
    <%= form.label :title, class:"formLabel" %>
    <%= form.text_field :title, placeholder:"Blog post title", class: "formInput #{'border-red-500' if form.object.errors.has_key?(:title)}" %>
    <% if form.object.errors.has_key?(:title) %>
      <p class="errorMessage"><%= form.object.errors[:title].first %></p>
    <% end %>
  </div>
  <div class="mb-4">
    <%= form.label :body, class:"formLabel" %>
    <%= form.text_area :body,size: "70x5", placeholder:"Blog post content", class: "formInput #{'border-red-500' if form.object.errors.has_key?(:body)}" %>
    <% if form.object.errors.has_key?(:body) %>
      <p class="errorMessage"><%= form.object.errors[:body].first %></p>
    <% end %>
  </div>
  <div>
    <%= form.label :published_at, class:"formLabel" %>
    <%= form.datetime_select :published_at, include_blank:true  %>
  </div>
  <div class="mt-4 flex">
    <% if form.object.new_record? %>
      <%= form.button "Create Post", class: "submitButton" %>
    <% else %>
      <%= form.button "Update Post", class: "submitButton" %>
    <% end %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="container mx-auto card">
  <h1 class="heading text-center mb-4">Update your blog post!</h1>
  <div class="p-4">
    <%= render partial: 'form', locals: { blog_post: @blog_post } %>
  </div>
</div>

app/views/blog_posts/index.html.erb
<div class='bg-slate-100 shadow-lg rounded-lg p-4 max-w-3xl mx-auto'>
  <div>
    <% if @blog_posts.present? %>
      <% @blog_posts.each_with_index do |blog_post,index|%>
        <div class="pb-4 border-b-2 <%= 'border-none' if index == @blog_posts.length - 1 %>">
          <div class='mt-2'>
            <h2 class='font-semibold text-indigo-700 mt-2 inline'><%= link_to blog_post.title , blog_post_path(blog_post.id)%></h2>
            <% if blog_post.draft? %>
              <span class="badge text-red-600 bg-red-200">Draft</span>
            <% elsif blog_post.scheduled? %>
              <span class="badge text-yellow-600 bg-yellow-200">Scheduled</span>
            <% else %>
              <span class="badge text-green-600  bg-green-200 ">Published</span>
            <% end %>
          </div>
          <p class ='text-base text-gray-800 mb-4'><%= blog_post.body%></p>
        </div>
      <%end%>
    <% else %>
      <h1 class='text-center text-gray-800 font-semibold mt-4'>You have not created any posts yet! To write your first blog post click on the button below.</h1>
    <% end %>
    <%if user_signed_in?%>
      <div class='flex justify-center'>
        <%= link_to "Create a new blog" ,new_blog_post_path ,class:"createButton block max-w-fit mt-4"%>
      </div>
    <%end%>
  </div>
</div>
<%# These two would also word because now blog_post is an activeRecord object and rails would know how to retrieve path and id from it!!!!! %>
<%# <h2 class='font-semibold text-indigo-700 mt-2'><%= link_to blog_post.title , blog_post_path</h2>%>
<%# <h2 class='font-semibold text-indigo-700 mt-2'><%= link_to blog_post.title , blog_post</h2>%>

app/views/blog_posts/new.html.erb
<div class="container mx-auto card">
  <h1 class="heading text-center mb-4">Add a new blog post here!</h1>
  <%# This code creates a form using the form_with helper method that will be associated with an instance of the BlogPost model (@blog_post instance variable). %>
  <%# The form_with method takes a model option which specifies the object (in this case @blog_post) that the form should be associated with. The form variable inside the block can be used to generate form input fields for the model attributes. %>
  <%# The form will be submitted to the controller's create action by default, as it was not specified in the form_with method. %>
  <%# The controller's action that the form will be submitted to can be specified by passing the url or action options to the form_with method. For example, if you want to submit the form to a different controller action than the default one, you can specify it like this: %>
  <%# local: true option specifies that the form should be submitted using AJAX, which is optional. %>
  <%# No, the :title symbol used in form.text_field :title and form.label :title is used to identify the attribute of the form's associated model that the field is for and label is referring to. It does not automatically fill in the value of the input. However, if the model instance @blog_post has a value for the title attribute, it will be shown as the value of the input field by default. %>
  <div class="p-4">
    <%= render partial: 'form', locals: { blog_post: @blog_post } %>
  </div>
</div>

app/views/blog_posts/show.html.erb
<div class='card my-8 max-w-3xl mx-auto'>
  <div>
    <div>
      <h1 class="font-semibold text-2xl text-gray-900 inline"><%= @blog_post.title%></h1>
      <% if @blog_post.draft? %>
        <span class="badge text-red-600 bg-red-200">Draft</span>
      <% elsif @blog_post.scheduled? %>
        <span class="badge text-yellow-600 bg-yellow-200">Scheduled</span>
      <% else %>
        <span class="badge text-green-600  bg-green-200 ">Published</span>
      <% end %>
    </div>
    <p><%= @blog_post.body%></p>
  </div>
  <div class='flex items-center mt-4 '>
    <%= link_to 'Edit blog' , edit_blog_post_path(@blog_post) , class:"editButton max-w-fit"%>
    <%= button_to "Delete Post", blog_post_path(@blog_post.id), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "deleteButton ml-2" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-gray-300 p-4 mt-8">
  <h1 class="text-gray-700 font-semibold text-lg text-center">&copy; Copyright: Go Rails</h1>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-indigo-700 p-4 mb-8 flex justify-between items-center">
  <%= link_to "My Awesome Blog Posts!", root_path, class:'text-white font-semibold text-2xl'%>
  <%if user_signed_in?%>
    <div class='flex items-center space-x-2'>
      <%= link_to "Profile" ,edit_user_registration_path , class:"bg-gray-100 text-gray-800 px-3 py-2 rounded-md hover:bg-gray-200"%>
      <%= button_to "Sign out",destroy_user_session_path	, method: :delete , class:'text-gray-50'%>
    </div>
  <%else%>
    <div class='space-x-2'>
      <%= link_to "Log in", new_user_session_path, class:'bg-gray-100 text-gray-800 px-3 py-2 rounded-md hover:bg-gray-200'%>
      <%= link_to "Sign up", new_user_registration_path	, class:'text-gray-50'%>
    </div>
  <%end%>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="flex flex-col min-h-screen">
    <%= render 'layouts/header' %>
    <main class="flex-1">
      <%if notice%>
        <div class='noticeToastWrapper'>
          <p class="notice  text-gray-700 "><%= notice %></p>
        </div>
      <%end%>
      <%if alert%>
        <div class='noticeToastWrapper'>
          <p class="alert"><%= alert %></p>
        </div>
      <%end%>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>